version: '3'
services:
  app:
    build: ./
    ports:
      - 18080:8080
    depends_on:
      - minio
      - mongo
    environment:
      - SPRING_PROFILE=dev
      - MONGODB_DB=dev
      - MONGODB_HOST=host.docker.internal
      - MONGODB_PASSWORD=example
      - MONGODB_USER=root
  minio:
    image: minio/minio
    ports:
      - 19000:9000
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server /data
  mongo:
    image: mongo
    ports:
      - 17017:27017
    environment:
      - MONGO_INITDB_DATABASE=dev
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  mongo-express:
    image: mongo-express
    ports:
      - 18081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
