amazon:
  aws:
    s3:
      accessKey: ${S3_ACCESSKEY:minioadmin}
      host: ${S3_HOST:http://localhost}
      port: ${S3_PORT:9090}
      region: ${S3_REGION:eu-central-1}
      secretKey: ${S3_SECRETKEY:minioadmin}
logging:
  level:
    ROOT: INFO
    org:
      hibernate: INFO
      mongodb: INFO
      springframework:
        web: INFO
server:
  port: ${SERVER_PORT:8080}
slog:
  paging:
    size: 10
spring:
  data:
    mongodb:
      user: nc
      password: V8L6dkDVMCHKbhY
      uri: mongodb+srv://cluster0.vaxu4.mongodb.net/slog_dev?retryWrites=true&w=majority
  output:
    ansi:
      enabled: ALWAYS
