amazon:
  aws:
    accessKey: ${AWS_ACCESSKEY:minioadmin}
    region: ${AWS_REGION:eu-central-1}
    secretKey: ${AWS_SECRETKEY:minioadmin}
logging:
  level:
    ROOT: INFO
    org:
      flywaydb: WARN
      hibernate: WARN
      springframework:
        web: WARN
server:
  port: ${SERVER_PORT:8080}
slog:
  paging:
    size: 10
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb
    username: sa
  flyway:
    locations: classpath:/db/migration,classpath:/db/seed
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  output:
    ansi:
      enabled: ALWAYS
