amazon:
  aws:
    s3:
      accessKey: ${S3_ACCESSKEY:minioadmin}
      host: ${S3_HOST:http://localhost}
      port: ${S3_PORT:9090}
      region: ${S3_REGION:eu-central-1}
      secretKey: ${S3_SECRETKEY:minioadmin}
logging:
  level:
    ROOT: INFO
    org:
      hibernate: WARN
      mongodb: WARN
      springframework:
        web: WARN
mongock:
  change-logs-scan-package: hu.netcode.slog.changelog
server:
  port: ${SERVER_PORT}
slog:
  paging:
    size: 10
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:root}:${MONGODB_PASSWORD:example}@${MONGODB_HOST:mongo}/${MONGODB_DB:prod}?retryWrites=true&w=majority
  output:
    ansi:
      enabled: ALWAYS
